name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *" # Ejecuta todos los días a medianoche
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: HectorLep
          outputs: |
            ./dist/github-contribution-grid-snake.svg

      - name: Push the generated snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
